### ISSUE TITLE
Broken CSS

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/project-issue-tracker-guide#1]
I put 

let winningCombos = {
  [0,1,2],[0,3,8],[0,4,8],[3,4,5],
  [2,3,6],[1,4,7],[6,7,8],[2,7,8]
};

in my gamelogic.js file, and required it in my index.js file. This breaks the CSS and throws an error that says invalid token at the first comma. I believe my object of arrays winningCombos is valid.

**Comment by gaand** [comment]
@jdamiron You want to file issue against [game-project](/ga-wdi-boston/game-project/issues).

The issue here is you have values without keys in an object literal.

**Comment by jdamiron** [comment]
Is this the correct way?

let winningCombos = {
  combo1:[0,1,2],
  combo2:[0,3,8],
  combo3:[0,4,8],
  combo4:[3,4,5],
  combo5:[2,3,6],
  combo6:[1,4,7],
  combo7:[6,7,8],
  combo8:[2,7,8]
};

**Comment by jdamiron** [comment]
Or should I let winningCombos = each array with no {} braces?

**Comment by jdamiron** [comment]
@gaand

**Comment by gaand** [comment]
Square braces `[]` or curly `{}` _with_ names.  If you're using winningCombos as an array, square braces.

**Comment by gaand** [comment]
@jdamiron I'm going to close this issue and reference it from a new issue on  [game-project](/ga-wdi-boston/game-project/issues).

**Comment by gaand** [comment]
See: ga-wdi-boston/game-project#6
