### ISSUE TITLE
Add note regarding issue request and personal matters

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/project-issue-tracker-guide#11]
Make developers aware that if they have issues, that they are embarrassed about putting in the issue queue. (i.e. personal matters, etc.). They should open an issue requesting a 1-on-1 about finishing the project and discuss matters in a private setting. 

Difference between reasons and agenda. @jrhorn424.

**Comment by gaand** [comment]
I think this opens us up to  "I need a 1-on-1" issues for those that aren't actually embarrassed, etc.  

If we don't have any sense of what the 1-on-1 is meant to address, how do we triage or push back when every developer asks for a 1-on-1?  This would seem to make the issue queue much less useful.

I don't know if either of these necessarily addresses the issue, but how about an e-mail or slack message asking for a 1-on-1 on a personal matter?

@ga-wdi-boston/core
