### ISSUE TITLE
js w/jquery -- getting linter errors on $ and require

### ISSUE THREAD

**Issue by ioncrash** [ga-wdi-boston/project-issue-tracker-guide#14]
tried copying in .jshintrc etc from browser template, and adding 

```html
<script src="vendor.bundle.js" type="text/javascript" charset="utf-8" defer></script>
      <script src="bundle.js" type="text/javascript" charset="utf-8" defer></script>
```

do I need to do something else to import jquery?

**Comment by ioncrash** [comment]
Sorry, error message is "$ is not defined" and "require is not defined"

**Comment by gaand** [comment]
This is not the correct repository for game project issues. Please close this issue and open one on https://github.com/ga-wdi-boston/game-project.
