### ISSUE TITLE
Local Site is Pausing in Debugger With no debuggers

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/project-issue-tracker-guide#15]
Whenever I refresh my local site the debugger is thrown.
I can hit play and the site loads normally
there are no errors in console
this happened after I went through steps to add the sign-in part of API
Asked a peer who was unsure of cause

**Comment by gaand** [comment]
@akradin This is not the repository for game project issues.  Please close this issue and open on at https://github.com/ga-wdi-boston/game-project/issues.

Thanks.
