### ISSUE TITLE
I am having trouble figuring out heroku

### ISSUE THREAD

**Issue by treep78** [ga-wdi-boston/project-issue-tracker-guide#18]
I cannot for the life of me get heroku working. I keep getting things like "app does not exist", and "'heroku' does not appear to be a git repository". I'm very confused and could use some help.

**Comment by gaand** [comment]
This is not the correct repository for project issues. Please open an issue on the full-stack-project repository and close this one. Thanks.

**Comment by treep78** [comment]
ok....
