### ISSUE TITLE
Reset button bug

### ISSUE THREAD

**Issue by antleo1995** [ga-wdi-boston/project-issue-tracker-guide#27]
Trying to reset the game state and it has introduced a bug:

```js
let playerIs = 'X'
let numOfMoves = 1
let gameOver = false
let board = ['', '', '', '', '', '', '', '', '']
$('.numOfMovesDiv').text('0')
$('.playerDiv').text(playerIs)

const putMarker = function () {

  if (this.innerHTML === '&nbsp;' && gameOver === false) {
    $(this).text(playerIs)
    $(this).show()
    const id = $(this).attr('id')
    console.log(id)
    board[id] = playerIs
    gameOver = checkVictory.checkVictory(playerIs, board, numOfMoves, gameOver)
    console.log(gameOver)
    if (gameOver === false) {
      $('.playerDiv').text(playerIs)
      $('.numOfMovesDiv').text(numOfMoves)
      numOfMoves += 1
    // console.log(board)
      if (playerIs === 'X') {
        playerIs = 'O'
        $('.playerDiv').text(playerIs)
      } else playerIs = 'X'
      $('.playerDiv').text(playerIs)
    } else (console.log('GameOver'))
  }
}

const resetBoard = function () {
  $('td').text(String.fromCharCode(160))
  board = ['', '', '', '', '', '', '', '', '']
  numOfMoves = 0
  playerIs = 'X'
  $('.playerDiv').text(playerIs)
  $('.numOfMovesDiv').text(numOfMoves)
  gameOver = false
}
```
After I hit the reset button, it breaks the ability to put my clicked data into it's proper spot in the array. 
Output in console looks like this:
["", "", "", "", "", "", "", "", "", undefined: "O"]
2017-04-06 15:34:28.892 game-logic.js:37 No One has won!. Checking for Tie
2017-04-06 15:34:28.892 game-events.js:19 false
2017-04-06 15:34:29.246 game-events.js:16 undefined
2017-04-06 15:34:29.246 game-logic.js:3 ["", "", "", "", "", "", "", "", "", undefined: "X"]
2017-04-06 15:34:29.247 game-logic.js:37 No One has won!. Checking for Tie
2017-04-06 15:34:29.247 game-events.js:19 false

**Comment by antleo1995** [comment]
Nevermind...figured it out:
$('td').text(String.fromCharCode(160))

Was apparently removing the div tag IDs I was using. So...I just set each div tag manually back to blank and that seemed to work. :)

**Comment by jrhorn424** [comment]
@antleo1995 Please open future issues on `ga-wdi-boston/game-project`. Please close this issue since you solved it.

**Comment by antleo1995** [comment]
Ah, I see...my bad. :) Closing
