### ISSUE TITLE
Grunt Deploy: Fatal error unable to find local grunt

### ISSUE THREAD

**Issue by Pouk91** [ga-wdi-boston/project-issue-tracker-guide#29]
$ grunt deploy
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started

My grunt isn't installed locally. I'm using the ubuntu OS. I've tried sudo npm install and the install was successful but the file still isn't able to found when i run grunt deploy.

**Comment by benjimelito** [comment]
Want to close this, and open under `game-project`instead?
