### ISSUE TITLE
Dropdown menu blocking game board

### ISSUE THREAD

**Issue by shireen-bean** [ga-wdi-boston/project-issue-tracker-guide#8]
could not click game spots on game board because dropdown menu was blocking it.

Solved: commented out dropdown menu and it works.
Note: bootstrap dropdowns work fine at the top, but if you put them at the bottom of the page (did that just temporarily) then it does weird things.

**Comment by shireen-bean** [comment]
Moved the dropdown back to the top of the screen and all was well again.

[Thanks Brian!]

**Comment by gaand** [comment]
@shkherad This is the wrong repository for game project issues.

If you still need assistance, please close this issue and open a new one on the game-project repository. If not, please close this issue. Thanks.
