### ISSUE TITLE
Sign Up POST issue

### ISSUE THREAD

**Issue by jlmitch1989** [ga-wdi-boston/project-issue-tracker-guide#9]
Issue Description:
I can't get my "Sign Up" button to actually save the username and password.

[ what you were doing when the problem showed up ]

[ error message (as text), if one exists ]
In my Dev Tool console it reads "undefined" when trying to  sign up with a new username and password.

[ the code that caused the error (as a fenced code block) or ] ```js

`$(()=>{
  $('.sign-up').on('click', function(){
    // console.log('You clicked sign up');
    $('#sign-up-modal').modal('show');
    $('.save-sign-up').on('click', function(){
      // console.log('you clicked save sign out');
      $('#sign-up-modal').modal('hide');
      let user = $('#username-info-su').val();
      console.log(user);
    });
  });
});`

[ things you've tried to fix the problem ]
Looking back at class notes, reading google searches, talking to classmates

**Comment by gaand** [comment]
This is on the wrong repository.  Please close this and reopen on `game-project`.  Thanks.
